In [9]:
import torch
a=torch.tensor([4,3], dtype=torch.float16)
print(a,a.dtype)

tensor([4., 3.], dtype=torch.float16) torch.float16


In [23]:
b=torch.ones(5,4)
c=torch.rand(4,4)
print(b@c)
print(b,b.dtype)

tensor([[2.5945, 2.2458, 1.9470, 2.1886],
        [2.5945, 2.2458, 1.9470, 2.1886],
        [2.5945, 2.2458, 1.9470, 2.1886],
        [2.5945, 2.2458, 1.9470, 2.1886],
        [2.5945, 2.2458, 1.9470, 2.1886]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) torch.float32


In [26]:
print(torch.Tensor([1.3,4,2]))

tensor([1.3000, 4.0000, 2.0000])


In CPU tensors share same memory location so if we change one variable associated with other, the other one also changes.
We can use .clone() to avoid having same memory location

In [37]:
b=a.view(-1)
c=a.clone()
b[1]=21
c[1]=23
print(a)
print(b)
print(c)


tensor([ 4., 21.], dtype=torch.float16)
tensor([ 4., 21.], dtype=torch.float16)
tensor([ 4., 23.], dtype=torch.float16)


`Gradients`

In [55]:
x=torch.randn(3,requires_grad=True)
y=x**3
print(x)
print(y)
z=y**2+y
print(z)



tensor([ 0.8969,  0.0696, -0.5814], requires_grad=True)
tensor([ 7.2150e-01,  3.3753e-04, -1.9653e-01], grad_fn=<PowBackward0>)
tensor([ 1.2421e+00,  3.3765e-04, -1.5791e-01], grad_fn=<AddBackward0>)


In [57]:
z=z.mean()
print(z)
z.backward()
print(x.grad)

tensor(0.3615, grad_fn=<MeanBackward0>)
tensor([1.9652, 0.0049, 0.2052])


We Need to update the grad to 0 after every epoch we use optimizer.zero_grad()

In [59]:
a=torch.randn(3,requires_grad=True)
b=a.detach()
print(a.requires_grad)
print(b.requires_grad)
b.requires_grad_(True)
print(b.requires_grad)

True
False
True


In [61]:
a=torch.randn(3,4 ,requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
    b=a+3
    print(b.requires_grad)



True
False


In [80]:
v=torch.randn(2,2)
k=torch.ones(2,2)
print(v@k)
print(torch.mm(v,k))

tensor([[-0.5387, -0.5387],
        [ 2.3877,  2.3877]])
tensor([[-0.5387, -0.5387],
        [ 2.3877,  2.3877]])
